#SPDX-FileCopyrightText: 2017-2024 Enedis
#SPDX-License-Identifier: Apache-2.0

name: "Build all"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build-all-template.yml
    with:
      skipTests: ${{ startsWith(github.head_ref, 'release/') }}
      cache-artifacts: |
        chutney/server/target/chutney-server-*.jar
        kotlin-dsl/target/chutney-kotlin-dsl-*.jar
